[package]
name = "mtgrust"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
enum-kinds = "0.5.1"
rand = "0.8.5"
ron = "0.8.1"
serde_json = "1"
serde_with = "3"
strum = "0.26.3"
strum_macros = "0.26.4"

[dependencies.serde]
version = "1"
features = ["derive"]
